version: "3.11"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: Courses
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_SERVERNAME} 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - HASH_ROUNDS=${HASH_ROUNDS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ZOOM_CLIENT_ID=${ZOOM_CLIENT_ID}
      - ZOOM_ACCOUNT_ID=${ZOOM_ACCOUNT_ID}
      - ZOOM_CLIENT_SECRET=${ZOOM_CLIENT_SECRET}
      - ZOOM_REDIRECT_OAUTH_LINK=${ZOOM_REDIRECT_OAUTH_LINK}
      - ZOOM_DEFAULT_LINK=${ZOOM_DEFAULT_LINK}
      - PAYME_KEY=${PAYME_KEY}
      - WAITING_TRANSACTIONS_MINUTES=${WAITING_TRANSACTIONS_MINUTES}
      - CLIENT_VERIFY_LINK=${CLIENT_VERIFY_LINK}
      - SERVER_VERIFY_LINK=${SERVER_VERIFY_LINK}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes: 
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads 
    depends_on:
      - postgres
    user: "root"

  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  
  postgres:
    image: postgres:13
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.0-alpine
    restart: always
    ports:
      - "6379:6379"

  migrate:
    build: .
    volumes:
      - '.:/app'
      - /app/node_modules
    command: npm run seeders
    depends_on:
      - postgres
      - app

volumes:
  postgres-data: null
  redis-data: null

